### ISSUE TITLE
Menu icon not showing and not customizable

### ISSUE THREAD

**Issue by alefz3r0** [smartin85/ionic-context-menu#2]
It seems that "more" is not a standard icon anymore, and the icon property in ionic-context-menu.component.ts is not an @Input

So, no menu icon is showing and it is not possible to set a custom icon.

How to fix this?

Many thanks

**Comment by alefz3r0** [comment]
As a quick fix, I have added a more.svg icon to assets/svg/, and added the following lines to angular.json:

```
              {
                "glob": "**/*.svg",
                "input": "src/assets/svg",
                "output": "./svg"
              }
```

**Comment by smartin85** [comment]
icon is now an @Input()
